version: "3"
services: 
    pluto-rover-api:
        build: 
          context: .
          dockerfile: Dockerfile
        image: "pluto-rover-api"
        ports:
          - "9199:9199"
        volumes: 
          - logs-pluto-rover-api:/logs/pluto-rover-api
volumes: 
  logs-pluto-rover-api: